import { Posts as PostsComponent } from "@/components/Posts";
import { Header } from "@/components/header";
import Head from "next/head";

const Posts = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PostsComponent />
    </div>
  );
};
export default Posts;
