import Posts from "@/components/Posts";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Posts />
    </div>
  );
};
export default Home;
